CREATE DATABASE customer_behaviour;
USE customer_behaviour;
show databases
USE customer_behaviour;

SELECT * FROM customer_data;

-- -- Q1 Calculate total revenue generated by each gender
select gender, Sum(purchase_amount) as revenue
from customer_data
group by gender;

-- -- Q2 Show customers who used a coupon and made purchases higher than the average purchase amount 
select customer_id, purchase_amount 
from customer_data
where discount_applied = 'Yes' and purchase_amount > (select avg(purchase_amount) from customer_data );

-- Q3 Find the top 5 products with the highest average review ratings
select item_purchased, round(avg(review_rating),2) as average_product_rating
from customer_data
group by item_purchased
order by avg(review_rating) desc
limit 5;

-- Q4 Compare Standard and Express shipping types based on average purchase amount
select shipping_type, 
round(avg(purchase_amount),2)
from customer_data
where shipping_type in ('express', 'standard')
group by shipping_type;

-- Q5 Analyze customer spending based on subscription status, including total customers, average spend, and total spend
select subscription_status, 
count('Customer ID') as total_customer,
round(avg(purchase_amount), 2) as average_spend,
round(SUM(purchase_amount), 2) as total_spend
from customer_data
group by subscription_status
order by average_spend,total_spend desc;

-- Q6 Find the percentage of purchases made using discounts for each product
select item_purchased, 
round(100* sum(case when discount_applied = 'Yes' then 1 else 0 end)/count(*),2) as discount_rate_in_percentage
from customer_data
group by item_purchased
order by discount_rate_in_percentage desc
limit 5;

-- Q7 Classify customers as New, Returning, or Loyal based on previous purchases
with customer_type as(
	select customer_id, previous_purchases,
    case
    when previous_purchases =1 then 'New'
    when previous_purchases between 2 and 10 then 'Returning_customer'
    else 'loyal_customer'
    end as customer_segment
    from customer_data
)
select customer_segment, count(*) as 'Number of customers'
from customer_type
group by customer_segment;

-- Q8 Rank the top 3 products in each category based on total orders
with item_counts as (
	select category, item_purchased,
    count(customer_id) as total_orders,
    row_number() over(partition by category order by count(customer_id) desc) as item_rank
    from customer_data
    group by category, item_purchased
)
select item_rank,category, item_purchased, total_orders
from item_counts
where item_rank <=3;

-- Q9 Find whether repeat customers are subscribed or not
select subscription_status, 
count(customer_id) as repeat_buyers
from customer_data
where previous_purchases > 5
group by subscription_status;

-- Q10 Identify which age group generated the highest revenue
select age_group, sum(purchase_amount) as total_revenue
from customer_data
group by age_group
order by total_revenue desc;